name: bleTalkNov2017
version: '0.1.0.0'
category: Music
author: Julian K. Arni
maintainer: jkarni@gmail.com
copyright: (c) 2017 Julian K. Arni
license: BSD3
github: jkarni/bleTalkNov2017

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - ble >= 0.4 && < 0.5
  - process >= 1.4 && < 1.5
  - vivid

library:
  source-dirs: src
  exposed-modules:
  - Lib

executables:
  exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bleTalkNov2017

tests:
  bleTalkNov2017-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

    dependencies:
      - bleTalkNov2017
